@startuml CancelarTurno


actor Paciente


boundary "PantallaCancelacion" as pantalla
control "ServicioCancelacion" as servicio
entity "Turno" as turno
entity "Agenda" as agenda
control "Notificacion" as notificacion


Paciente -> pantalla : solicitarCancelacion(idTurno)


pantalla -> servicio : validarCancelacion(idTurno)


servicio -> turno : buscarTurno(idTurno)


turno --> servicio : devolverDatosTurno()


servicio -> agenda : liberarHorario(fecha, hora)


agenda --> servicio : horarioLiberado()


servicio -> turno : cancelarTurno(idTurno)


turno --> servicio : turnoCancelado()


servicio -> notificacion : enviarCancelacion(paciente, fecha, hora)


notificacion --> servicio : cancelacionEnviada()


destroy notificacion


servicio --> pantalla : mostrarConfirmacionCancelacion()


pantalla --> Paciente : informarTurnoCancelado()


@enduml
