@startuml

rectangle "Sistema de Turnos Médicos" {
  usecase "Agendar Turno" as UC1
actor Paciente

Paciente --> (Visualizar turnos disponibles)
Paciente --> (Agendar turno)
Paciente --> (Cancelar turno)

(Agendar turno) --> (Validar disponibilidad) : <<include>>
(Agendar turno) --> (Visualizar turnos disponibles) : <<include>>

(Cancelar turno) --> (Notificar cancelación) : <<include>>

}
@enduml