@startuml
actor Paciente

Paciente --> (Visualizar turnos disponibles)
Paciente --> (Agendar turno)
Paciente --> (Cancelar turno)

(Agendar turno) --> (Validar disponibilidad) : <<include>>
(Agendar turno) --> (Visualizar turnos disponibles) : <<include>>

(Cancelar turno) --> (Notificar cancelación) : <<extend>>

@enduml