@startuml
actor Secretaria
actor Medico

Secretaria --> (Agendar turno)
Secretaria --> (Reprogramar turno)
Secretaria --> (Cancelar turno)
Secretaria --> (Registrar llegada del paciente)

Medico --> (Atender turno)
Medico --> (Consultar turnos del día)

(Agendar turno) --> (Validar disponibilidad) : <<include>>
(Reprogramar turno) --> (Validar disponibilidad) : <<include>>

(Cancelar turno) --> (Notificar cancelación) : <<extend>>

(Registrar llegada del paciente) --> (Registrar hora real de llegada) : <<include>>
(Registrar llegada del paciente) --> (Notificar al médico) : <<include>>

@enduml