@startuml
actor Secretaria
actor Medico

Secretaria --> (Agendar turno)
Secretaria --> (Reprogramar turno)
Secretaria --> (Cancelar turno)
Secretaria --> (Registrar llegada del paciente)

Medico --> (Atender turno)
Medico --> (Consultar turnos del día)

(Registrar llegada del paciente) --> (Registrar hora real de llegada) : <<include>>

(Agendar turno) --> (Registrar historial de cambios) : <<include>>
(Reprogramar turno) --> (Registrar historial de cambios) : <<include>>
(Cancelar turno) --> (Registrar historial de cambios) : <<include>>
(Registrar llegada del paciente) --> (Registrar historial de cambios) : <<include>>

@enduml