@startuml name
actor Secretaria
actor Medico

Secretaria --> (Gestionar disponibilidad de horarios)
Secretaria --> (Bloquear horario por vacaciones o feriado)
Secretaria --> (Configurar horario habitual)

Medico --> (Asignar sobreturno)

(Gestionar disponibilidad de horarios) --> (Bloquear horario por vacaciones o feriado) : <<include>>
(Gestionar disponibilidad de horarios) --> (Configurar horario habitual) : <<include>>

(Gestionar disponibilidad de horarios) --> (Validar reglas del consultorio) : <<include>>
(Asignar sobreturno) --> (Validar reglas del consultorio) : <<include>>

@enduml