@startuml

class Paciente {
  nombre
  dni
  fechaNacimiento
  telefono
  mail
  pedirTurno()
  cancelarTurno()
  verHorariosDisponibles()
}

class Medico {
  nombre
  apellido
  telefono
  mail
  especialidad
  matricula
  consultarAgenda()
  atenderConsulta()
  definirDisponibilidad()
  autorizarSobreturno()
}

class Turno {
  fecha
  hora
  estado
  tipoConsulta
  duracionPrevista
  duracionReal
  esSobreturno
  reservar()
  cancelar()
  reprogramar()
  confirmar()
}

class Secretaria {
  nombre
  apellido
  telefono
  mail
  agendarTurno()
  reprogramarTurno()
  cancelarTurno()
  notificarPaciente()
}

class Agenda {
  fechaActual
  vistaActual
  mostrarAgendaDiaria()
  mostrarAgendaSemanal()
  agregarTurno()
  eliminarTurno()
  verificarConflicto()
}

class Disponibilidad {
  dia
  horaInicio
  horaFin
  estado
  tipoBloque
  bloquearHorario()
  habilitarHorario()
  esDisponible()
}

Paciente --> Turno
Medico --> Turno
Medico --> Agenda
Medico --> Disponibilidad
Secretaria --> Turno
Secretaria --> Agenda
Agenda --> Turno
Agenda --> Disponibilidad
Turno --> Disponibilidad

@enduml